import Link from "next/link";
import { Badge, PageShell, PageVisual } from "./ui";
import { JsonLd, absoluteUrl, breadcrumbSchema } from "./seo";

const data={
 germany:{flag:'🇩🇪',name:'Germany',title:'Germany Packaging Compliance for Non-EU Sellers',lead:'If you are established outside Germany and sell packaged products directly to German consumers, German packaging/EPR requirements may apply to your business.',terms:[['▣','PPWR','The EU-wide Packaging and Packaging Waste Regulation.'],['♻','EPR','Extended Producer Responsibility for packaging placed on a market.'],['◎','Producer','The entity identified under the applicable, effective legal definition.'],['✓','LUCID','Germany’s packaging register operated by ZSVR.'],['◇','System participation','Participation in a relevant recycling system where required.'],['▦','Packaging reporting','Periodic reporting of packaging quantities under applicable rules.']],source:'German Central Agency Packaging Register — ZSVR / LUCID',sourceUrl:'https://www.verpackungsregister.org/en/'},
 france:{flag:'🇫🇷',name:'France',title:'France Packaging EPR for International Sellers',lead:'Selling packaged goods to consumers in France may trigger producer responsibility, identification, PRO participation and reporting steps.',terms:[['♻','Packaging EPR','Responsibility for certain packaging placed on the French market.'],['◎','Producer responsibility','Status depends on the effective definition and your sales model.'],['✓','Identification','Applicable identifiers and registration steps must be verified.'],['◇','PRO participation','A producer responsibility organisation may be part of the route.'],['▦','Reporting','Quantities and cadence depend on current rules and scheme guidance.'],['▣','PPWR interaction','EU and national requirements must be read together as they take effect.']],source:'French Ministry for Ecological Transition',sourceUrl:'https://www.ecologie.gouv.fr/politiques-publiques/cadre-general-filieres-responsabilite-elargie-producteurs'},
 italy:{flag:'🇮🇹',name:'Italy',title:'Italy Packaging EPR for International Sellers',lead:'International sellers placing packaged products on the Italian market should assess CONAI, EPR and packaging contribution obligations against current verified rules.',terms:[['✓','CONAI','Italy’s National Packaging Consortium.'],['♻','EPR','Extended Producer Responsibility for packaging.'],['▣','Packaging materials','Material categories can affect registration, reporting and contributions.'],['€','Environmental contributions','Applicable contributions depend on current scheme rules.'],['◎','Producer / importer','Responsibility depends on the effective national definition and supply chain.'],['◇','PPWR interaction','The EU regulation and national implementation must be tracked together.']],source:'Italian National Packaging Consortium — CONAI',sourceUrl:'https://www.conai.org/en/'}
} as const;

export function CountryPage({country}:{country:keyof typeof data}){
 const d=data[country];
 return <PageShell>
  <JsonLd data={[breadcrumbSchema([{name:'Home',path:'/'},{name:'Countries',path:'/countries'},{name:d.name,path:`/countries/${country}`}]),{"@context":"https://schema.org","@type":"Service","name":d.title,"description":d.lead,"provider":{"@id":`${absoluteUrl('/') }#organization`},"areaServed":{"@type":"Country","name":d.name},"url":absoluteUrl(`/countries/${country}`)}]} />
  <section className="page-hero country-hero"><div className="shell"><div><div className="crumb"><Link href="/countries">Countries</Link> / {d.name}</div><Badge>Country compliance guide</Badge><h1>{d.title}</h1><p>{d.lead}</p><div className="actions"><Link className="button primary" href="/checker">Check my requirements →</Link><span className="verified"><i/> Last verified: 12 August 2026</span></div></div><div className="country-flag">{d.flag}</div></div></section>
  <PageVisual label={`${d.name.toUpperCase()} GUIDANCE`} title="See the market, packaging flow and evidence in one place."/>
  <div className="content-shell article-layout"><article className="article"><div className="notice">Requirements are generated from the regulatory database. Where a current official source has not been reviewed, the platform shows “Verification required”.</div><h2>What international sellers need to understand</h2><p>{d.lead} The exact route depends on who places the packaging on the market, how products are sold, the kind of packaging used, and the effective rules on the relevant date.</p><div className="steps country-topic-grid">{d.terms.map(x=><div className="step-card" key={x[1]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</div><h2>{d.name} compliance wizard</h2><ol><li>Confirm the business establishment and sales model.</li><li>Map sales, e-commerce and transport packaging.</li><li>Verify producer status against the effective rule.</li><li>Complete registrations and scheme participation where required.</li><li>Coordinate an eligible local partner where the law requires one.</li><li>Report packaging and retain dated evidence.</li></ol>{country==='germany'&&<p className="notice">Where an authorised representative is legally required, we can coordinate onboarding with an eligible German partner.</p>}<h2>PPWR and national rules</h2><p>Regulation (EU) 2025/40 generally applies from 12 August 2026. National registration, EPR and reporting requirements may interact with PPWR and can change. The checker therefore evaluates rules by effective date and verification status.</p></article><aside><div className="panel info-card sticky"><h2>Official sources</h2><a className="source" href={d.sourceUrl} target="_blank" rel="noreferrer"><span aria-hidden>↗</span><div><b>{d.source}</b><small>Primary regulatory source</small></div></a><a className="source" href="https://eur-lex.europa.eu/eli/reg/2025/40/oj/eng" target="_blank" rel="noreferrer"><span aria-hidden>↗</span><div><b>EUR-Lex</b><small>Regulation (EU) 2025/40</small></div></a><p><b>Last checked</b><br/>12 August 2026</p><p><b>Legal review status</b><br/><span className="tag review">Review in progress</span></p><Link className="button primary" style={{width:'100%'}} href="/checker">Start country check</Link></div></aside></div>
 </PageShell>
}
