import Link from "next/link";
import { AppShell } from "./app-shell";

const markets=[["🇩🇪","Germany","Registration review","4 open","required"],["🇫🇷","France","EPR review","5 open","review"],["🇮🇹","Italy","Evidence pending","3 open","verify"]];

export function DashboardView({displayName="Leyla",demo=false}:{displayName?:string;demo?:boolean}){return <AppShell>
  {demo&&<div className="demo-banner"><b>Interactive product demo</b><span>Sample data only. No legal conclusion or verified customer status is shown.</span><Link href="/login">Create an account →</Link></div>}
  <div className="app-top"><div><span className="workspace-kicker">EU COMPLIANCE PASSPORT</span><h1>Good morning, {displayName}</h1><p>Your route from country check to reporting, in one workspace.</p></div><div className="avatar">{displayName.slice(0,2).toUpperCase()}</div></div>
  <div className="passport-banner"><div><small>BUSINESS PROFILE</small><h2>Leyla Studio</h2><p>Azerbaijan · Etsy + Shopify · Jewellery · 3 EU destinations</p></div><div className="profile-meter"><span><b>68%</b> profile complete</span><div><i style={{width:"68%"}}/></div></div><Link className="button light" href="/checker">Complete passport</Link></div>
  <div className="journey-tabs" aria-label="Compliance workflow"><span className="done">1 Check</span><span className="active">2 Country actions</span><span>3 Registration</span><span>4 Reporting</span><span>5 Renewals</span></div>
  <div className="dashboard-grid">
    <section className="dash-card market-actions"><div className="card-title-row"><div><h2>Country actions</h2><p>Statuses reflect available rules and evidence—not assumptions.</p></div><Link href="/checker">Run new check →</Link></div><div className="country-action-head"><span>Market</span><span>Next workflow</span><span>Actions</span><span>Status</span></div>{markets.map(x=><div className="country-action" key={x[1]}><span className="flag">{x[0]}</span><b>{x[1]}</b><span>{x[2]}</span><strong>{x[3]}</strong><span className={`tag ${x[4]}`}>{x[4]==="required"?"Action needed":x[4]==="review"?"Review":"Verify"}</span></div>)}<div className="evidence-rule">“Compliant” appears only after the required supporting evidence has been verified.</div></section>
    <section className="dash-card"><div className="card-title-row"><div><h2>Annual packaging</h2><p>Across current shipment profiles</p></div><Link href="/calculator">Edit →</Link></div><div className="stat-grid"><div className="stat"><b>8.2 kg</b><span>Cardboard</span></div><div className="stat"><b>1.3 kg</b><span>Paper</span></div><div className="stat"><b>0.7 kg</b><span>Plastic</span></div></div><div className="notice compact-notice">Reporting categories and simplified reporting are not the same as an exemption.</div></section>
    <section className="dash-card"><div className="card-title-row"><div><h2>Compliance calendar</h2><p>Dates are activated only from verified rules.</p></div><span className="tag review">2 upcoming</span></div><div className="deadline"><i>18</i><p><b>Germany packaging report</b><br/><small>18 days remaining</small></p></div><div className="deadline"><i>32</i><p><b>France declaration review</b><br/><small>32 days remaining</small></p></div><div className="deadline"><i>—</i><p><b>Italy reporting date</b><br/><small>Verification required</small></p></div></section>
    <section className="dash-card"><div className="card-title-row"><div><h2>Evidence vault</h2><p>Marketplace-ready records and documents</p></div><span className="vault-count">4 files</span></div><div className="vault-list"><div><span>PDF</span><p><b>Producer information sheet</b><small>Germany · Onboarding</small></p><em className="tag ok">Ready</em></div><div><span>AGR</span><p><b>System participation agreement</b><small>Germany · EPR</small></p><em className="tag review">Missing</em></div><div><span>CSV</span><p><b>Packaging summary 2026</b><small>All destinations · Report</small></p><em className="tag ok">Generated</em></div></div></section>
  </div>
</AppShell>}
