import Link from "next/link";
import { Badge, PageShell, PageVisual } from "./ui";

const details: Record<string, { title: string; copy: string; items: string[] }> = {
  Etsy: { title: "A practical route for independent marketplace sellers.", copy: "Made-to-order products often use several layers of packaging, from presentation boxes and inserts to mailers and shipping cartons. Record each material and destination instead of relying on order value or business size.", items: ["Export Etsy destination and order totals", "Separate presentation and shipping packaging", "Review each EU country’s verified rule"] },
  Shopify: { title: "Connect store data to country-by-country packaging records.", copy: "Your own storefront gives you direct access to destinations, product variants and fulfilment records. Use that data to build packaging profiles and track what is shipped into each EU market.", items: ["Map checkout destinations", "Create packaging profiles by product", "Keep country evidence with each report"] },
  Amazon: { title: "Assess the seller, fulfilment route and destination together.", copy: "Marketplace and fulfilment arrangements can affect the facts that need review. The platform does not assume the marketplace has automatically resolved every packaging obligation for the seller.", items: ["Identify seller and fulfilment model", "Separate inventory and shipment packaging", "Verify requirements for each destination"] },
  "Handmade business": { title: "Small volumes still deserve a clear assessment.", copy: "A small or handmade business is not automatically exempt. Track actual packaging weights, then distinguish simplified reporting from any verified exemption under the rule effective for that country.", items: ["Count every EU destination", "Measure low-volume packaging accurately", "Check exemptions only against verified rules"] },
  "Jewellery brand": { title: "Separate durable cases from disposable packaging.", copy: "Jewellery orders may combine long-term storage cases, presentation packaging, pouches, inserts and shipping materials. A durable case can require an individual product-versus-packaging assessment.", items: ["Assess the function of durable cases", "Track pouches, inserts and mailers separately", "Keep product and packaging evidence together"] },
};

export function MarketplacePage({name,audience}:{name:string,audience:string}){const detail=details[name];return <PageShell><section className="page-hero country-hero"><div className="shell"><div><Badge>{name} EU compliance</Badge><h1>Selling on {name} to Germany?</h1><p>Check your packaging compliance before your next EU order. Get a clear, source-linked assessment built for {audience}.</p><div className="actions"><Link className="button primary" href="/checker">Check my EU requirements →</Link><Link className="button secondary" href="/pricing">View pricing</Link></div></div><div className="country-flag">EU</div></div></section><PageVisual label={`${name.toUpperCase()} SELLERS`} title={detail.title}/><section className="section shell center"><Badge>From sale to action plan</Badge><h2>Your marketplace does not replace your own compliance assessment.</h2><p className="section-lede">{detail.copy}</p><div className="steps">{detail.items.map((item,index)=><article className="step-card" key={item}><span>{String(index+1).padStart(2,'0')}</span><h3>{item}</h3><p>{index===0?'Start with reliable sales and destination data.':index===1?'Build an evidence trail that matches how you actually pack and ship.':'Use dated rules and official sources—not assumptions.'}</p></article>)}</div><div className="related-links" aria-label="Related compliance tools"><Link href="/calculator">Calculate packaging weight →</Link><Link href="/assessment">Assess product vs packaging →</Link><Link href="/countries">Browse all EU countries →</Link></div></section></PageShell>}
