"use client";
import { useMemo, useState } from "react";
import Link from "next/link";
import { businessCountries, euCountries } from "./country-data";

const channels=["Etsy","Shopify","Amazon","eBay","Own website","Social commerce"];
const products=["Jewellery","Clothing","Accessories","Cosmetics","Home decor","Art","Electronics","Toys","Handmade"];
const materials=["Cardboard","Paper","Plastic","Glass","Wood","Metal","Textile","Composite"];

export function Checker(){
 const [step,setStep]=useState(1); const [country,setCountry]=useState("Azerbaijan"); const [selected,setSelected]=useState<string[]>(["Etsy"]); const [product,setProduct]=useState("Jewellery"); const [dests,setDests]=useState<string[]>(["Germany"]); const [shipments,setShipments]=useState(25); const [weight,setWeight]=useState(80);
 const toggle=(x:string)=>setSelected(s=>s.includes(x)?s.filter(i=>i!==x):[...s,x]);
 const toggleDest=(x:string)=>setDests(s=>s.includes(x)?s.filter(i=>i!==x):[...s,x]);
 return <div className="content-shell tool-layout"><div className="panel"><div className="panel-head"><div><small className="muted-note">STEP {Math.min(step,3)} OF 3</small><h2>{step===1?'Your business':step===2?'Products & destination':'Your assessment'}</h2></div><span className="muted-note">{Math.round(Math.min(step,3)/3*100)}% complete</span></div><div className="progress" role="progressbar" aria-label="Assessment progress" aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.round(Math.min(step,3)/3*100)}><i style={{width:`${Math.min(step,3)/3*100}%`}}/></div><div className="panel-body">
 {step===1&&<><div className="field"><label htmlFor="business-country">Where is your business established?</label><select id="business-country" value={country} onChange={e=>setCountry(e.target.value)}>{businessCountries.map(x=><option key={x}>{x}</option>)}</select></div><fieldset className="field form-fieldset"><legend>Where do you sell?</legend><div className="option-grid compact-options">{channels.map(x=><label className={`option ${selected.includes(x)?'selected':''}`} key={x}><input type="checkbox" checked={selected.includes(x)} onChange={()=>toggle(x)}/><span>{x}</span></label>)}</div></fieldset></>}
 {step===2&&<><div className="field"><label htmlFor="product-category">What do you sell?</label><select id="product-category" value={product} onChange={e=>setProduct(e.target.value)}>{products.map(x=><option key={x}>{x}</option>)}</select></div><fieldset className="field form-fieldset"><legend>Where do you sell in the EU?</legend><small>Select one or several countries.</small><div className="country-check-grid">{euCountries.map(x=><label className={`country-check ${dests.includes(x[0])?'selected':''}`} key={x[1]}><input type="checkbox" checked={dests.includes(x[0])} onChange={()=>toggleDest(x[0])}/><span aria-hidden>{x[2]}</span><b>{x[0]}</b></label>)}</div></fieldset><div className="calc-row"><div className="field"><label htmlFor="checker-material">Packaging material</label><select id="checker-material"><option>Cardboard</option>{materials.slice(1).map(x=><option key={x}>{x}</option>)}</select></div><div className="field"><label htmlFor="checker-weight">Weight / order</label><input id="checker-weight" value={weight} onChange={e=>setWeight(+e.target.value)} type="number" min="0"/></div><div className="field"><label htmlFor="checker-orders">Annual orders</label><input id="checker-orders" value={shipments} onChange={e=>setShipments(+e.target.value)} type="number" min="0"/></div></div></>}
 {step>=3&&<div><div className="verified"><i/> Assessment prepared from versioned country records</div><h2 style={{margin:'18px 0 6px'}}>Your country action plan</h2><p className="muted-note">{dests.length?dests.join(', '):'No destination selected'} · Business in {country} · {product} · {selected.join(', ')}</p><div className="checker-market-list">{dests.map((dest,i)=><article key={dest}><div className="checker-market-title"><div><span>{euCountries.find(c=>c[0]===dest)?.[2]}</span><h3>{dest}</h3></div><b>{4+i} actions to review</b></div><div className="result-line"><span>Potential producer status</span><b className="tag review">Review required</b></div><div className="result-line"><span>Producer registration</span><b className="tag verify">Verification required</b></div><div className="result-line"><span>EPR / system participation</span><b className="tag verify">Verification required</b></div><div className="result-line"><span>Service cost estimate</span><b className="tag verify">Quote after verification</b></div></article>)}</div><div className="result-total"><small>ESTIMATED ANNUAL PACKAGING</small><strong>{(weight*shipments/1000).toFixed(2)} kg</strong><div className="material-result"><span>Cardboard</span><b>{(weight*shipments/1000).toFixed(2)} kg/year</b></div></div><h3>Recommended next steps</h3><ol className="muted-note" style={{fontSize:13,lineHeight:1.9}}><li>Verify producer status against the effective country rule.</li><li>Complete any verified registration and system participation actions.</li><li>Coordinate an eligible local partner where legally required.</li><li>Store evidence for marketplace checks and future reporting.</li></ol><div className="notice">No categorical legal conclusion is shown where a verified, effective rule is unavailable. A low sales volume is not treated as an automatic exemption. This informational assessment is not legal advice.</div></div>}
 </div><div className="tool-footer"><button className="button secondary" onClick={()=>setStep(Math.max(1,step-1))} disabled={step===1}>Back</button>{step<3?<button className="button primary" onClick={()=>setStep(step+1)}>Continue →</button>:<Link className="button primary" href="/dashboard">Make me compliant →</Link>}</div></div><aside className="panel info-card"><div className="verified"><i/> Privacy-first assessment</div><h3>What you’ll get</h3><ul><li>Potential producer status</li><li>Registration and EPR indicators</li><li>AR / partner coordination prompt</li><li>Packaging weight estimate</li><li>Traceable next steps</li></ul><hr style={{border:0,borderTop:'1px solid #e3ebf2',margin:'20px 0'}}/><h3>Regulatory data</h3><p>Results are designed to come from versioned country rules with effective dates, official sources and human verification status.</p><p><b>Last regulatory update</b><br/>12 August 2026</p></aside></div>
}

type Row={name:string;grams:number};
export function Calculator(){const [orders,setOrders]=useState(25);const [rows,setRows]=useState<Row[]>([{name:'Cardboard box',grams:80},{name:'Paper',grams:10},{name:'Plastic',grams:5}]);const total=useMemo(()=>rows.reduce((a,r)=>a+r.grams*orders/1000,0),[rows,orders]);const update=(i:number,key:keyof Row,val:string)=>setRows(rows.map((r,n)=>n===i?{...r,[key]:key==='grams'?+val:val}:r));return <div className="content-shell tool-layout"><div className="panel"><div className="panel-head"><h2>Packaging profile</h2><span className="muted-note">Profile: Standard jewellery order</span></div><div className="panel-body"><div className="field"><label htmlFor="calculator-orders">Annual orders to Germany</label><input id="calculator-orders" type="number" min="0" value={orders} onChange={e=>setOrders(+e.target.value)}/></div><h3 style={{fontSize:13}}>Materials per shipment</h3>{rows.map((r,i)=><div className="calc-row" key={i}><div className="field"><label htmlFor={`material-${i}`}>Material / item</label><input id={`material-${i}`} value={r.name} onChange={e=>update(i,'name',e.target.value)}/></div><div className="field"><label htmlFor={`grams-${i}`}>Weight (g)</label><input id={`grams-${i}`} type="number" min="0" value={r.grams} onChange={e=>update(i,'grams',e.target.value)}/></div><div className="field"><label htmlFor={`annual-${i}`}>Annual kg</label><input id={`annual-${i}`} readOnly value={(r.grams*orders/1000).toFixed(3)}/></div><button type="button" aria-label={`Remove ${r.name}`} onClick={()=>setRows(rows.filter((_,n)=>n!==i))}>×</button></div>)}<button type="button" className="button secondary" onClick={()=>setRows([...rows,{name:'New material',grams:0}])}>+ Add material</button><div className="notice" style={{marginTop:22}}>Keep sales packaging, e-commerce packaging and transport packaging separate where the applicable reporting system distinguishes them.</div></div></div><aside><div className="result-total" aria-live="polite"><small>ANNUAL TOTAL</small><strong>{total.toFixed(3)} kg</strong>{rows.map((r,i)=><div className="material-result" key={i}><span>{r.name}</span><b>{(r.grams*orders/1000).toFixed(3)} kg</b></div>)}<button type="button" className="button light" style={{width:'100%',marginTop:18}}>Save to my account</button></div><div className="panel info-card" style={{marginTop:14}}><h3>Calculation</h3><p>Weight per shipment × annual orders ÷ 1,000 = annual kilograms.</p><p>Multiple product and packaging profiles can be managed from the full dashboard.</p></div></aside></div>}
