import Link from "next/link";
import Image from "next/image";
import type { ReactNode } from "react";

export function Arrow(){return <span aria-hidden>→</span>}
export function Badge({children}:{children:ReactNode}){return <div className="eyebrow"><i/> {children}</div>}
export function Logo(){return <Link className="logo" href="/" aria-label="Complisera homepage"><span className="logo-mark" aria-hidden>C</span><span>Compli<b>sera</b></span></Link>}
export function Header(){return <header className="site-header"><div className="shell nav"><Logo/><nav aria-label="Primary navigation"><Link href="/checker">Checker</Link><Link href="/calculator">Calculator</Link><Link href="/assessment">Assessment</Link><Link href="/countries">Countries</Link><Link href="/pricing">Pricing</Link><Link href="/partners">Partners</Link></nav><div className="nav-actions"><label className="language" aria-label="Language"><select defaultValue="en" aria-label="Interface language"><option value="en">EN</option><option value="ru">RU</option><option value="az">AZ</option><option value="tr">TR</option></select></label><Link className="login" href="/login">Log in</Link><Link className="button small primary" href="/checker">Start free</Link></div></div></header>}
export function Footer(){return <footer><div className="shell footer-grid"><div><Logo/><p>Subscription compliance management software for selling across Europe.</p><div className="language-pills" aria-label="Planned interface languages"><span>EN</span><span>RU</span><span>AZ</span><span>TR</span></div></div><nav aria-label="Product links"><b>Product</b><Link href="/checker">PPWR Checker</Link><Link href="/calculator">Packaging calculator</Link><Link href="/demo">Product demo</Link><Link href="/pricing">Pricing</Link></nav><nav aria-label="Country guidance links"><b>Guidance</b><Link href="/countries">All 27 EU countries</Link><Link href="/countries/germany">Germany</Link><Link href="/countries/france">France</Link><Link href="/countries/italy">Italy</Link><Link href="/knowledge">Knowledge base</Link></nav><nav aria-label="Legal and support links"><b>Legal & support</b><Link href="/legal/terms">Terms of Service</Link><Link href="/legal/privacy">Privacy Policy</Link><Link href="/legal/subscriptions">Subscriptions & cancellation</Link><Link href="/legal/refunds">Refund Policy</Link><Link href="/legal">Disclaimer</Link><Link href="/support">Customer support</Link></nav></div><div className="shell footer-bottom"><span>© 2026 Complisera · Operated from Azerbaijan</span><span>Compliance management software · Regulatory information · Not legal advice</span></div></footer>}
export function CountryPill({flag,name,detail,href}:{flag:string,name:string,detail:string,href:string}){return <Link className="country-pill" href={href}><span className="flag">{flag}</span><span><b>{name}</b><small>{detail}</small></span><Arrow/></Link>}
export function MiniDashboard(){return <div className="mini-shell"><div className="mini-top"><div className="dot-menu"><i/><i/><i/></div><span>Compliance overview</span><b>•••</b></div><div className="score-card"><div><small>EU COMPLIANCE SCORE</small><strong>72<span>%</span></strong><p>4 actions to review</p></div><div className="score-ring"><span>72</span></div></div><div className="mini-title"><b>Your markets</b><span>3 countries</span></div>{[['🇩🇪','Germany','Action required','orange'],['🇫🇷','France','Under review','blue'],['🇮🇹','Italy','Verification needed','gray']].map(x=><div className="mini-country" key={x[1]}><span className="flag">{x[0]}</span><b>{x[1]}</b><span className={`status ${x[3]}`}>{x[2]}</span><span>›</span></div>)}<div className="mini-update"><span>↻</span><p><b>Rules checked today</b><small>Sources are versioned and traceable</small></p></div></div>}

export function PageShell({children}:{children:ReactNode}){return <><Header/><main>{children}</main><Footer/></>}
export function PageVisual({label,title}:{label:string,title:string}){return <section className="page-visual shell" aria-label={label}><div><span>{label}</span><h2>{title}</h2><div className="page-visual-points"><b>✓ Official sources</b><b>▦ Versioned rules</b><b>◇ Clear next steps</b></div></div><Image src="/eu-compliance-network.png" alt="Parcels, a European map and a compliance verification shield" width={1536} height={1024} loading="lazy" sizes="(max-width: 600px) 100vw, (max-width: 900px) 50vw, 54vw"/></section>}
